name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # https://docs.github.com/en/rest/releases/releases#create-a-release
      # https://docs.github.com/en/rest/releases/assets#upload-a-release-asset
      - name: Create release and upload assets
        run: |
          RELEASE="$(curl \
                       --silent \
                       --show-error \
                       --fail \
                       --request POST \
                       --url https://api.github.com/repos/${{github.repository}}/releases \
                       --data '{"tag_name":"${{github.ref_name}}","name":"${{github.repository}} ${{github.ref_name}}","draft":false,"prerelease":false}' \
                       --header "Accept: application/vnd.github.v3+json" \
                       --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq '.id')" && \
          curl \
            --silent \
            --show-error \
            --fail \
            --request POST \
            --url https://uploads.github.com/repos/${{github.repository}}/releases/${RELEASE}/assets?name=containerdiag.sh \
            --header "Accept: application/vnd.github.v3+json" \
            --header "Content-Type: $(file -b --mime-type containerdiag.sh)" \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --data-binary @containerdiag.sh
